/** 内置新手词包：4 个考纲高频词包，每包 40 词 */

export interface PackWord {
  word: string
  phonetic: string
  meaning: string
}

export interface WordPack {
  id: string
  name: string
  desc: string
  words: PackWord[]
}

export const WORD_PACKS: WordPack[] = [
  {
    id: 'gaokao',
    name: '高考核心',
    desc: '考纲高频 3500 词中的核心动词与名词',
    words: [
      { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: 'v. 实现；取得' },
      { word: 'adapt', phonetic: '/əˈdæpt/', meaning: 'v. 适应；改编' },
      { word: 'benefit', phonetic: '/ˈbenɪfɪt/', meaning: 'n. 益处；v. 受益' },
      { word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', meaning: 'n. 挑战；v. 向…挑战' },
      { word: 'consequence', phonetic: '/ˈkɒnsɪkwəns/', meaning: 'n. 结果；后果' },
      { word: 'contribute', phonetic: '/kənˈtrɪbjuːt/', meaning: 'v. 贡献；促成' },
      { word: 'demand', phonetic: '/dɪˈmɑːnd/', meaning: 'v./n. 要求；需求' },
      { word: 'despite', phonetic: '/dɪˈspaɪt/', meaning: 'prep. 尽管' },
      { word: 'determine', phonetic: '/dɪˈtɜːmɪn/', meaning: 'v. 决定；确定' },
      { word: 'develop', phonetic: '/dɪˈveləp/', meaning: 'v. 发展；培养' },
      { word: 'effect', phonetic: '/ɪˈfekt/', meaning: 'n. 影响；效果' },
      { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: 'n. 环境' },
      { word: 'establish', phonetic: '/ɪˈstæblɪʃ/', meaning: 'v. 建立' },
      { word: 'evidence', phonetic: '/ˈevɪdəns/', meaning: 'n. 证据' },
      { word: 'experience', phonetic: '/ɪkˈspɪəriəns/', meaning: 'n. 经历；经验' },
      { word: 'explore', phonetic: '/ɪkˈsplɔː/', meaning: 'v. 探索' },
      { word: 'focus', phonetic: '/ˈfəʊkəs/', meaning: 'v./n. 集中；焦点' },
      { word: 'improve', phonetic: '/ɪmˈpruːv/', meaning: 'v. 改进；提高' },
      { word: 'increase', phonetic: '/ɪnˈkriːs/', meaning: 'v. 增加' },
      { word: 'influence', phonetic: '/ˈɪnfluəns/', meaning: 'n./v. 影响' },
      { word: 'involve', phonetic: '/ɪnˈvɒlv/', meaning: 'v. 涉及；包含' },
      { word: 'knowledge', phonetic: '/ˈnɒlɪdʒ/', meaning: 'n. 知识' },
      { word: 'maintain', phonetic: '/meɪnˈteɪn/', meaning: 'v. 维持；主张' },
      { word: 'measure', phonetic: '/ˈmeʒə/', meaning: 'v. 测量；n. 措施' },
      { word: 'method', phonetic: '/ˈmeθəd/', meaning: 'n. 方法' },
      { word: 'opportunity', phonetic: '/ˌɒpəˈtjuːnəti/', meaning: 'n. 机会' },
      { word: 'particular', phonetic: '/pəˈtɪkjələ/', meaning: 'adj. 特定的；挑剔的' },
      { word: 'perform', phonetic: '/pəˈfɔːm/', meaning: 'v. 执行；表演' },
      { word: 'pressure', phonetic: '/ˈpreʃə/', meaning: 'n. 压力' },
      { word: 'process', phonetic: '/ˈprəʊses/', meaning: 'n. 过程；v. 处理' },
      { word: 'produce', phonetic: '/prəˈdjuːs/', meaning: 'v. 生产；产生' },
      { word: 'purpose', phonetic: '/ˈpɜːpəs/', meaning: 'n. 目的' },
      { word: 'reduce', phonetic: '/rɪˈdjuːs/', meaning: 'v. 减少' },
      { word: 'require', phonetic: '/rɪˈkwaɪə/', meaning: 'v. 需要；要求' },
      { word: 'responsible', phonetic: '/rɪˈspɒnsəbl/', meaning: 'adj. 负责的' },
      { word: 'significant', phonetic: '/sɪɡˈnɪfɪkənt/', meaning: 'adj. 重要的；显著的' },
      { word: 'situation', phonetic: '/ˌsɪtʃuˈeɪʃn/', meaning: 'n. 情况；形势' },
      { word: 'society', phonetic: '/səˈsaɪəti/', meaning: 'n. 社会' },
      { word: 'suggest', phonetic: '/səˈdʒest/', meaning: 'v. 建议；表明' },
      { word: 'survey', phonetic: '/ˈsɜːveɪ/', meaning: 'n./v. 调查' },
    ],
  },
  {
    id: 'cet4',
    name: '四级核心',
    desc: 'CET-4 真题高频词，覆盖阅读与写作',
    words: [
      { word: 'abandon', phonetic: '/əˈbændən/', meaning: 'v. 放弃；抛弃' },
      { word: 'absorb', phonetic: '/əbˈzɔːb/', meaning: 'v. 吸收；使专注' },
      { word: 'academic', phonetic: '/ˌækəˈdemɪk/', meaning: 'adj. 学术的' },
      { word: 'bargain', phonetic: '/ˈbɑːɡən/', meaning: 'n. 便宜货；v. 讨价还价' },
      { word: 'capacity', phonetic: '/kəˈpæsəti/', meaning: 'n. 容量；能力' },
      { word: 'circumstance', phonetic: '/ˈsɜːkəmstəns/', meaning: 'n. 情况；环境' },
      { word: 'commit', phonetic: '/kəˈmɪt/', meaning: 'v. 承诺；犯（罪）' },
      { word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', meaning: 'v. 交流；传达' },
      { word: 'compare', phonetic: '/kəmˈpeə/', meaning: 'v. 比较' },
      { word: 'compete', phonetic: '/kəmˈpiːt/', meaning: 'v. 竞争' },
      { word: 'concern', phonetic: '/kənˈsɜːn/', meaning: 'v. 涉及；n. 关心' },
      { word: 'confident', phonetic: '/ˈkɒnfɪdənt/', meaning: 'adj. 自信的' },
      { word: 'confirm', phonetic: '/kənˈfɜːm/', meaning: 'v. 确认；证实' },
      { word: 'consume', phonetic: '/kənˈsjuːm/', meaning: 'v. 消耗；消费' },
      { word: 'contact', phonetic: '/ˈkɒntækt/', meaning: 'n./v. 联系' },
      { word: 'critical', phonetic: '/ˈkrɪtɪkl/', meaning: 'adj. 关键的；批评的' },
      { word: 'decade', phonetic: '/ˈdekeɪd/', meaning: 'n. 十年' },
      { word: 'decline', phonetic: '/dɪˈklaɪn/', meaning: 'v./n. 下降；谢绝' },
      { word: 'definite', phonetic: '/ˈdefɪnət/', meaning: 'adj. 明确的' },
      { word: 'deliver', phonetic: '/dɪˈlɪvə/', meaning: 'v. 递送；发表' },
      { word: 'efficient', phonetic: '/ɪˈfɪʃnt/', meaning: 'adj. 高效的' },
      { word: 'emphasis', phonetic: '/ˈemfəsɪs/', meaning: 'n. 强调' },
      { word: 'enable', phonetic: '/ɪˈneɪbl/', meaning: 'v. 使能够' },
      { word: 'essential', phonetic: '/ɪˈsenʃl/', meaning: 'adj. 必要的；本质的' },
      { word: 'estimate', phonetic: '/ˈestɪmeɪt/', meaning: 'v./n. 估计' },
      { word: 'expand', phonetic: '/ɪkˈspænd/', meaning: 'v. 扩大；扩展' },
      { word: 'exposure', phonetic: '/ɪkˈspəʊʒə/', meaning: 'n. 暴露；接触' },
      { word: 'feature', phonetic: '/ˈfiːtʃə/', meaning: 'n. 特征；v. 以…为特色' },
      { word: 'finance', phonetic: '/ˈfaɪnæns/', meaning: 'n. 财政；金融' },
      { word: 'flexible', phonetic: '/ˈfleksəbl/', meaning: 'adj. 灵活的' },
      { word: 'function', phonetic: '/ˈfʌŋkʃn/', meaning: 'n. 功能；v. 运转' },
      { word: 'guarantee', phonetic: '/ˌɡærənˈtiː/', meaning: 'v./n. 保证' },
      { word: 'identity', phonetic: '/aɪˈdentəti/', meaning: 'n. 身份；同一性' },
      { word: 'individual', phonetic: '/ˌɪndɪˈvɪdʒuəl/', meaning: 'adj. 个人的；n. 个人' },
      { word: 'invest', phonetic: '/ɪnˈvest/', meaning: 'v. 投资' },
      { word: 'issue', phonetic: '/ˈɪʃuː/', meaning: 'n. 问题；v. 发布' },
      { word: 'opposite', phonetic: '/ˈɒpəzɪt/', meaning: 'adj. 相反的' },
      { word: 'relevant', phonetic: '/ˈreləvənt/', meaning: 'adj. 相关的' },
      { word: 'resource', phonetic: '/rɪˈsɔːs/', meaning: 'n. 资源' },
      { word: 'strategy', phonetic: '/ˈstrætədʒi/', meaning: 'n. 战略；策略' },
    ],
  },
  {
    id: 'cet6',
    name: '六级核心',
    desc: 'CET-6 高频学术词汇，写作提分利器',
    words: [
      { word: 'alleviate', phonetic: '/əˈliːvieɪt/', meaning: 'v. 减轻；缓和' },
      { word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', meaning: 'adj. 模棱两可的' },
      { word: 'compensate', phonetic: '/ˈkɒmpenseɪt/', meaning: 'v. 补偿；弥补' },
      { word: 'comprehensive', phonetic: '/ˌkɒmprɪˈhensɪv/', meaning: 'adj. 全面的；综合的' },
      { word: 'controversial', phonetic: '/ˌkɒntrəˈvɜːʃl/', meaning: 'adj. 有争议的' },
      { word: 'crucial', phonetic: '/ˈkruːʃl/', meaning: 'adj. 至关重要的' },
      { word: 'cumulative', phonetic: '/ˈkjuːmjələtɪv/', meaning: 'adj. 累积的' },
      { word: 'deliberate', phonetic: '/dɪˈlɪbərət/', meaning: 'adj. 故意的；慎重的' },
      { word: 'deteriorate', phonetic: '/dɪˈtɪəriəreɪt/', meaning: 'v. 恶化' },
      { word: 'diminish', phonetic: '/dɪˈmɪnɪʃ/', meaning: 'v. 减少；贬低' },
      { word: 'eliminate', phonetic: '/ɪˈlɪmɪneɪt/', meaning: 'v. 消除；淘汰' },
      { word: 'exaggerate', phonetic: '/ɪɡˈzædʒəreɪt/', meaning: 'v. 夸大' },
      { word: 'feasible', phonetic: '/ˈfiːzəbl/', meaning: 'adj. 可行的' },
      { word: 'fluctuate', phonetic: '/ˈflʌktʃueɪt/', meaning: 'v. 波动' },
      { word: 'genuine', phonetic: '/ˈdʒenjuɪn/', meaning: 'adj. 真正的；真诚的' },
      { word: 'hypothesis', phonetic: '/haɪˈpɒθəsɪs/', meaning: 'n. 假设' },
      { word: 'implement', phonetic: '/ˈɪmplɪment/', meaning: 'v. 实施；n. 工具' },
      { word: 'implicit', phonetic: '/ɪmˈplɪsɪt/', meaning: 'adj. 含蓄的；固有的' },
      { word: 'inevitable', phonetic: '/ɪnˈevɪtəbl/', meaning: 'adj. 不可避免的' },
      { word: 'ingredient', phonetic: '/ɪnˈɡriːdiənt/', meaning: 'n. 成分；要素' },
      { word: 'initiative', phonetic: '/ɪˈnɪʃətɪv/', meaning: 'n. 主动性；倡议' },
      { word: 'integrity', phonetic: '/ɪnˈteɡrəti/', meaning: 'n. 正直；完整' },
      { word: 'intervene', phonetic: '/ˌɪntəˈviːn/', meaning: 'v. 干预；介入' },
      { word: 'legitimate', phonetic: '/lɪˈdʒɪtɪmət/', meaning: 'adj. 合法的；正当的' },
      { word: 'manipulate', phonetic: '/məˈnɪpjuleɪt/', meaning: 'v. 操纵；操作' },
      { word: 'negligible', phonetic: '/ˈneɡlɪdʒəbl/', meaning: 'adj. 可忽略的' },
      { word: 'obscure', phonetic: '/əbˈskjʊə/', meaning: 'adj. 模糊的；v. 使模糊' },
      { word: 'overwhelming', phonetic: '/ˌəʊvəˈwelmɪŋ/', meaning: 'adj. 压倒性的' },
      { word: 'paradox', phonetic: '/ˈpærədɒks/', meaning: 'n. 悖论；矛盾' },
      { word: 'perceive', phonetic: '/pəˈsiːv/', meaning: 'v. 感知；认为' },
      { word: 'perspective', phonetic: '/pəˈspektɪv/', meaning: 'n. 视角；观点' },
      { word: 'phenomenon', phonetic: '/fəˈnɒmɪnən/', meaning: 'n. 现象' },
      { word: 'preliminary', phonetic: '/prɪˈlɪmɪnəri/', meaning: 'adj. 初步的' },
      { word: 'profound', phonetic: '/prəˈfaʊnd/', meaning: 'adj. 深刻的；深远的' },
      { word: 'redundant', phonetic: '/rɪˈdʌndənt/', meaning: 'adj. 多余的' },
      { word: 'scrutiny', phonetic: '/ˈskruːtəni/', meaning: 'n. 仔细检查' },
      { word: 'skeptical', phonetic: '/ˈskeptɪkl/', meaning: 'adj. 怀疑的' },
      { word: 'substantial', phonetic: '/səbˈstænʃl/', meaning: 'adj. 大量的；实质性的' },
      { word: 'trivial', phonetic: '/ˈtrɪviəl/', meaning: 'adj. 琐碎的' },
      { word: 'vulnerable', phonetic: '/ˈvʌlnərəbl/', meaning: 'adj. 脆弱的；易受伤的' },
    ],
  },
  {
    id: 'kaoyan',
    name: '考研核心',
    desc: '考研英语真题高频词，偏学术书面语',
    words: [
      { word: 'adhere', phonetic: '/ədˈhɪə/', meaning: 'v. 坚持；附着' },
      { word: 'advocate', phonetic: '/ˈædvəkeɪt/', meaning: 'v. 提倡；n. 拥护者' },
      { word: 'articulate', phonetic: '/ɑːˈtɪkjuleɪt/', meaning: 'v. 清晰表达；adj. 口齿清晰的' },
      { word: 'coherent', phonetic: '/kəʊˈhɪərənt/', meaning: 'adj. 连贯的；一致的' },
      { word: 'coincide', phonetic: '/ˌkəʊɪnˈsaɪd/', meaning: 'v. 同时发生；一致' },
      { word: 'compromise', phonetic: '/ˈkɒmprəmaɪz/', meaning: 'n./v. 妥协；折中' },
      { word: 'conceive', phonetic: '/kənˈsiːv/', meaning: 'v. 构想；设想' },
      { word: 'contemplate', phonetic: '/ˈkɒntəmpleɪt/', meaning: 'v. 沉思；考虑' },
      { word: 'contempt', phonetic: '/kənˈtempt/', meaning: 'n. 蔑视' },
      { word: 'deduce', phonetic: '/dɪˈdjuːs/', meaning: 'v. 推断；演绎' },
      { word: 'defy', phonetic: '/dɪˈfaɪ/', meaning: 'v. 违抗；蔑视' },
      { word: 'denote', phonetic: '/dɪˈnəʊt/', meaning: 'v. 表示；意指' },
      { word: 'derive', phonetic: '/dɪˈraɪv/', meaning: 'v. 获得；源自' },
      { word: 'elaborate', phonetic: '/ɪˈlæbərət/', meaning: 'adj. 详尽的；v. 详述' },
      { word: 'endeavor', phonetic: '/ɪnˈdevə/', meaning: 'v./n. 努力；尝试' },
      { word: 'exemplify', phonetic: '/ɪɡˈzemplɪfaɪ/', meaning: 'v. 举例证明' },
      { word: 'explicit', phonetic: '/ɪkˈsplɪsɪt/', meaning: 'adj. 明确的；直白的' },
      { word: 'facilitate', phonetic: '/fəˈsɪlɪteɪt/', meaning: 'v. 促进；使便利' },
      { word: 'formulate', phonetic: '/ˈfɔːmjuleɪt/', meaning: 'v. 系统阐述；制定' },
      { word: 'hierarchy', phonetic: '/ˈhaɪərɑːki/', meaning: 'n. 等级制度' },
      { word: 'illuminate', phonetic: '/ɪˈluːmɪneɪt/', meaning: 'v. 照亮；阐明' },
      { word: 'impair', phonetic: '/ɪmˈpeə/', meaning: 'v. 损害；削弱' },
      { word: 'incentive', phonetic: '/ɪnˈsentɪv/', meaning: 'n. 激励；刺激' },
      { word: 'incorporate', phonetic: '/ɪnˈkɔːpəreɪt/', meaning: 'v. 合并；包含' },
      { word: 'indispensable', phonetic: '/ˌɪndɪˈspensəbl/', meaning: 'adj. 不可或缺的' },
      { word: 'inferior', phonetic: '/ɪnˈfɪəriə/', meaning: 'adj. 次等的；下级的' },
      { word: 'intrinsic', phonetic: '/ɪnˈtrɪnzɪk/', meaning: 'adj. 内在的；固有的' },
      { word: 'manifest', phonetic: '/ˈmænɪfest/', meaning: 'v. 表明；adj. 明显的' },
      { word: 'mediate', phonetic: '/ˈmiːdieɪt/', meaning: 'v. 调解；斡旋' },
      { word: 'notorious', phonetic: '/nəʊˈtɔːriəs/', meaning: 'adj. 臭名昭著的' },
      { word: 'obligation', phonetic: '/ˌɒblɪˈɡeɪʃn/', meaning: 'n. 义务；责任' },
      { word: 'plausible', phonetic: '/ˈplɔːzəbl/', meaning: 'adj. 貌似合理的' },
      { word: 'precede', phonetic: '/prɪˈsiːd/', meaning: 'v. 先于；在…之前' },
      { word: 'prospect', phonetic: '/ˈprɒspekt/', meaning: 'n. 前景；可能性' },
      { word: 'rectify', phonetic: '/ˈrektɪfaɪ/', meaning: 'v. 纠正；整顿' },
      { word: 'refute', phonetic: '/rɪˈfjuːt/', meaning: 'v. 驳斥；反驳' },
      { word: 'scrutinize', phonetic: '/ˈskruːtənaɪz/', meaning: 'v. 仔细审查' },
      { word: 'spontaneous', phonetic: '/spɒnˈteɪniəs/', meaning: 'adj. 自发的' },
      { word: 'subordinate', phonetic: '/səˈbɔːdɪnət/', meaning: 'adj. 从属的；n. 下属' },
      { word: 'undermine', phonetic: '/ˌʌndəˈmaɪn/', meaning: 'v. 逐渐削弱；破坏' },
    ],
  },
]
